Release
nitrictech/node-sdk pull request #151
Opened 2022-11-28 02:12 UTC by jyecusch

2022-11-29 00:56 UTC, tjholm requested changes

2022-11-29 00:56 UTC, tjholm commented on package.json
> +  "nitric": "v0.20.0-rc.2",
Should promote this to a production release prior to rolling out.

2022-11-29 03:34 UTC, tjholm approved these changes

2022-11-30 00:36 UTC, HomelessDinosaur approved these changes

2022-11-30 03:21 UTC, merged